### ISSUE TITLE
Support to only share via specific apps?

### ISSUE THREAD

**Issue by Whyser** [yasirkula/UnityNativeShare#10]
Hey and thanks for this simple Unity Plugin!

I'm wondering if you're planning to add support to "force" user to use specific app to share through. I don't know how to do it straight off, but with some googling I can probably do it myself, but would be a great addition to this plugin!

Something like:
`new NativeShare.AddAppPackage("com.facebook.messenger").SetContent("Hello World").Share()`

I think this is only supported on Android though.

Anyway, thanks!

**Comment by yasirkula** [comment]
That sounds interesting. You are right that it won't support iOS but I might still give it a shot.

**Comment by Whyser** [comment]
Awesome! :D

**Comment by yasirkula** [comment]
I've added **SetTarget** function with the latest update, but it supports one app package only. So, you can't use it to e.g. narrow down the applications to Facebook and Twitter. I initially tried to support this functionality but then Twitter just stopped accepting the shared image, no matter what I tried. Feel free to implement it yourself, though, if it is a requirement of your project :)

**Comment by Whyser** [comment]
Sounds weird! Anyway, thanks a lot! If I need the functionality I will make sure to make a pull request. :)
