### ISSUE TITLE
 AndroidJavaException: java.lang.ClassNotFoundException: com.yasirkula.unity.NativeShare

### ISSUE THREAD

**Issue by aadi3124** [yasirkula/UnityNativeShare#100]
01-15 12:47:04.474 32050 32144 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: com.yasirkula.unity.NativeShare
01-15 12:47:04.474 32050 32144 E Unity   : java.lang.ClassNotFoundException: com.yasirkula.unity.NativeShare
01-15 12:47:04.474 32050 32144 E Unity   :      at java.lang.Class.classForName(Native Method)
01-15 12:47:04.474 32050 32144 E Unity   :      at java.lang.Class.forName(Class.java:453)
01-15 12:47:04.474 32050 32144 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
01-15 12:47:04.474 32050 32144 E Unity   :      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
01-15 12:47:04.474 32050 32144 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
01-15 12:47:04.474 32050 32144 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:102)
01-15 12:47:04.474 32050 32144 E Unity   :      at android.os.Looper.loop(Looper.java:201)
01-15 12:47:04.474 32050 32144 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
01-15 12:47:04.474 32050 32144 E Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yasirkula.unity.NativeShare" on path: DexPathList[[zip file "/data/app/com.litifer.android.myhoggy-xe4n-AJZpyz37yFpxooSUw==/base.apk"],nativeLibraryDirectories=[/data/app/com.litifer.android.myhoggy-xe4n-AJZpyz37yFpxooSUw==/lib/arm, /data/app/com.litifer.android.myhoggy-xe4n-AJZpyz37yFpxooSUw==/base.apk!/lib/armeabi-v7a, /system/lib]]
01-15 12:47:04.474 32050 32144 E Unity   :      at dalvik.s

I am adding -keep class com.yasirkula.unity.* { *; } this line in proguard but getting deleted by self and getting this error everytime. Please help! Thanks.

**Comment by yasirkula** [comment]
Which ProGuard file are you adding this line to?

**Comment by aadi3124** [comment]
Temp\gradleOut\unityLibrary/proguard-unity
inside this file, if i am wrong please suggest where to add

**Comment by yasirkula** [comment]
You need to enable Custom Proguard File in Player Settings and add the line to it. Everything inside Temp folder is temporary. You shouldn't touch the contents of Temp or Library folders.

**Comment by aadi3124** [comment]
Thanks a lot. It worked.
