### ISSUE TITLE
The type or namespace name 'NativeShare' could not be found

### ISSUE THREAD

**Issue by yinliguo** [yasirkula/UnityNativeShare#101]
The NativeShare plugin has been installed into Assets/Plugins, but the error occur.
I had try to restart unity and code editor(vscode) and reimport the plugin, it doesn't works.
Need I use "using" statement? If so, what is it?

Unity: 2019.4
NativeShare: 1.3.8(lastest currently)

**Comment by yinliguo** [comment]
Solved.
I delete some other files and change some code nothing about NativeShare, the error above disapear. weird.

**Comment by gputhread** [comment]
Telll how to solve unity 2020.3.14, i want to cal native share wherever its hiding!

**Comment by yasirkula** [comment]
If the error doesn't show up in Unity console, then it's an Intellisense issue. Otherwise, you must add NativeShare's assembly definition file to your own's Referenced Assemblies list.

**Comment by gputhread** [comment]
> If the error doesn't show up in Unity console, then it's an Intellisense issue. Otherwise, you must add NativeShare's assembly definition file to your own's Referenced Assemblies list.

yup it disappeared now from unity log..i moved it out of plugin folder which was not useful then i moved it back..its just vscode shwowing it now.

**Comment by yasirkula** [comment]
After closing VS Code, try **Edit-Preferences-External Tools-Regenerate project files**.

**Comment by gputhread** [comment]
> After closing VS Code, try **Edit-Preferences-External Tools-Regenerate project files**.

ok 😃👍
