### ISSUE TITLE
Namespace error when building projects for PC

### ISSUE THREAD

**Issue by hippogamesunity** [yasirkula/UnityNativeShare#106]
Hi! When I switch platform to PC (Mono) and try building my project I've got the error:

Assets\Plugins\NativeShare\NativeShare.cs(4,7): error CS0246: The type or namespace name 'NativeShareNamespace' could not be found (are you missing a using directive or an assembly reference?)

Can be fixed by adding #if UNITY_ANDROID || UNITY_IOS.

**Comment by yasirkula** [comment]
Does the latest version on GitHub have the same issue?

**Comment by hippogamesunity** [comment]
Yes, got the error right after today's update.

**Comment by yasirkula** [comment]
Yes, you are right. Dang it, first #93 and now this, so annoying. I'll fix it for good.

**Comment by yasirkula** [comment]
Closed in https://github.com/yasirkula/UnityNativeShare/commit/e91a8f46317a03264bf71c3d991cff6eb58867a5, hopefully. I won't be surprised if it isn't.

Thanks for reporting it 👍

**Comment by hippogamesunity** [comment]
No problem, thanks for making the asset!
