### ISSUE TITLE
How To Share Pre Define Image Using Native Share

### ISSUE THREAD

**Issue by Nameless77** [yasirkula/UnityNativeShare#110]
Hello i am currently working on a sudoku game and want to publish it on play store.in this game i have added a sharing functionality(ex. when user press button a native share dialogue popped up and then when user click a perticular app to share then my game image automatically apper in that app(for example of whats app the image is automatically set))so how can i do this with 
native plugin.i already tried with resource folder(i put my image in resource folder but i cant get any image from resource folder).so can you please tell how to so this.

**Comment by yasirkula** [comment]
You can call `Resources.Load<Texture2D>(texture path)` and pass the returned Texture2D to AddFile.

**Comment by Nameless77** [comment]
hello sir i am unable to share predefined image. as you mentioned i wrote some code here it is:
`public void Click_Share()
    {
        StartCoroutine(TakeScreenShotAndShare());
    }
    IEnumerator TakeScreenShotAndShare()
    {
        yield return new WaitForEndOfFrame();
        
        string filePath = Resources.Load<Texture2D>("Promo").ToString();
        new NativeShare().AddFile(filePath).SetSubject("Look at my Image").SetText("Hello world!")
        .SetUrl("https://play.google.com/store/apps/details?id=com.microsoft.sudoku").Share();
        // print(filePath);
    }`
and this is the image which i want to share from resource folder : 
![Screenshot 2021-05-03 133540](https://user-images.githubusercontent.com/53361101/116854032-ac998e00-ac14-11eb-8bae-ba2f8ee1ca16.png)
and on my android phone when i click on share button image was not loaded only text and url appear.
so can you please suggest me something it will be a great help.

**Comment by yasirkula** [comment]
```csharp
Texture2D image = Resources.Load<Texture2D>("Promo");
new NativeShare().AddFile(image).
```

**Comment by Nameless77** [comment]
Thank you sir this time it's working I thought that the file path should be
string.

**Comment by yasirkula** [comment]
AddFile can take either a file path or a Texture2D (for convenience).
