### ISSUE TITLE
Could no resolve all files for configuration ':unityLibrary:releaseCompileClasspath'. See the console for details.

### ISSUE THREAD

**Issue by Iamblank-ux** [yasirkula/UnityNativeShare#114]
![WhatsApp Image 2021-05-30 at 6 28 28 PM (1)](https://user-images.githubusercontent.com/63692047/120100848-903a3400-c175-11eb-8349-a9b226248c4d.jpeg)
![WhatsApp Image 2021-05-30 at 6 28 28 PM](https://user-images.githubusercontent.com/63692047/120100864-a0eaaa00-c175-11eb-9eba-30c38da667d6.jpeg)
Hi, I am using Unity vers 2019.3.13f1 and the whole set-up of native share was fine as it did print like shared in console when I press the share button but I am unable to build due to these build errors that I am not sure how to solve them. It would be nice to know what the solution is. Thanks in advance.

**Comment by yasirkula** [comment]
Are you sure that the issue is caused by NativeShare and not ARCore? I can't see NativeShare in the error logs.

**Comment by Iamblank-ux** [comment]
Hi Can I ask if there is a 1.3.8 version of native share that I can use as I think using that might solve my current problem?

**Comment by yasirkula** [comment]
There is. You can find all releases here: https://github.com/yasirkula/UnityNativeShare/releases
