### ISSUE TITLE
Sharing Image Issue on WhatsApp IOS

### ISSUE THREAD

**Issue by imran-nadeem** [yasirkula/UnityNativeShare#12]
Hi,
Your plugin is great and works fine on almost all the sharing platforms but when i try to share text and image on whatsapp then only text is shown in IOS while in android both image and text show up.
Can you check this that why whatsapp don't share image with text on IOS ?
I am using Unity 2017.3.1 and OS for Iphone is 9.2
Thanks

**Comment by yasirkula** [comment]
I don't think it is possible to share both:

- https://stackoverflow.com/questions/39977066/share-text-and-image-on-whatsapp-using-uiactivityviewcontroller
- https://github.com/mwaterfall/MWPhotoBrowser/issues/528
- https://stackoverflow.com/questions/40543420/objective-c-how-to-share-image-and-text-via-whatsapp-fb-uidocumentinteracti

**Comment by imran-nadeem** [comment]
Oh okay.
Thanks
