### ISSUE TITLE
Why can't I share on whatsapp in iOS, has this ability in android though

### ISSUE THREAD

**Issue by manisharan18** [yasirkula/UnityNativeShare#121]
Able to see all other sharable apps except whatsapp on iOS. I am trying to share an image with a text on through any sharable app. All others woks great. Why only not whatsapp.

Please guide me. Thanks.

**Comment by yasirkula** [comment]
I haven't heard of this before. You can't share text with image on WhatsApp but that doesn't mean that WhatsApp won't appear in the share sheet. I honestly don't know the cause of it. Perhaps reinstalling/updating WhatsApp resolves the issue?

**Comment by manisharan18** [comment]
Hi. Thanks for quick response. I tested again. Able to see whatsapp app in the apps list, but only text is appearing, there is no image attached.

Do I need to add any permission in info.plist to share image. I need to share image with text. Appreciate your help. Thanks.

**Comment by manisharan18** [comment]
Able to share image if I comment out .AddText method.

How to share both.

**Comment by yasirkula** [comment]
I wish it was possible but it isn't. Google "UIActivityViewController WhatsApp image with text" you'll see the same result.
