### ISSUE TITLE
[Android] Choose Nearby Share but cancel in the end. It will callback with the result : shared

### ISSUE THREAD

**Issue by jackchen1210** [yasirkula/UnityNativeShare#122]
**Description of the bug**

As Title.

**Reproduction steps**

1. Pop share dialog.
2. Click Nearby button.
3. Click X button.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2020.3.15f2
- Platform: Android
- Device: Google Pixel 3a, Android 11
- How did you download the plugin: GitHub v1.4.2

**Additional info**
None.

**Comment by yasirkula** [comment]
Quoting the documentation:

> **Shared:** user has probably shared the content. This value guarantees that the user has at least selected an app from the share sheet. But it is impossible to say whether the user has actually shared the content or cancelled the operation right after selecting the app from the share sheet
