### ISSUE TITLE
Error <queries>

### ISSUE THREAD

**Issue by akari23** [yasirkula/UnityNativeShare#124]
Hi , i wanna ask something
![image](https://user-images.githubusercontent.com/33738081/130073406-5e038688-6698-4c7d-8b2e-5d79a4862de4.png)
is that mean, i just delete this one?
![image](https://user-images.githubusercontent.com/33738081/130073556-88841896-7007-421e-a682-1593b4a25601.png)
without deletting the intent

or the delete the entire <queries> ?
thankyou sir

**Comment by yasirkula** [comment]
You should delete the entire thing.

**Comment by akari23** [comment]
> You should delete the entire thing.

Already delete , and make a new NativeShare.aar 
then now i can build, but when i click a button that contain share func, it wont open the share option, i cant see anything happen on android device

**Comment by yasirkula** [comment]
If you've recreated NativeShare.aar from scratch, I would instead recommend you to open NativeShare.aar, open AndroidManifest.xml, modify it, return to opened NativeShare.aar, when Winrar asks whether or not to update the archive say yes. That's how I do at least. If you've created the aar from scratch, you may have used a wrong compression and I suspect that NativeShare native classes aren't included in your build.

**Comment by akari23** [comment]
> If you've recreated NativeShare.aar from scratch, I would instead recommend you to open NativeShare.aar, open AndroidManifest.xml, modify it, return to opened NativeShare.aar, when Winrar asks whether or not to update the archive say yes. That's how I do at least. If you've created the aar from scratch, you may have used a wrong compression and I suspect that NativeShare native classes aren't included in your build.

it work so great!!!
thankyouu so much for ur help sir
