### ISSUE TITLE
After Package Import "NativeShare" can't be found in scripts

### ISSUE THREAD

**Issue by BielBG** [yasirkula/UnityNativeShare#136]
**Description of the bug**

After Package Import (either via the Asset Store or downloading the .unitypackage from here), I do have the NativeShare folder under /Plugins but I cannot use any of it's classes. It doesn't matter which script I open, if I write "NativeShare" it doesn't detect the class in my project. I've reloaded, reopened, reimported, everything.

**Reproduction steps**

- Install the plugin (either via Import Package or from the Asset Store).
- Try to use the classes to start sharing with the plugin but they don't "exist".

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *e.g. 2020.3.13f1*
- Platform: Windows Editor
- Device: --
- How did you download the plugin: Asset Store or downloading it from this github page.

![Sin título](https://user-images.githubusercontent.com/30040784/146793575-e9fcbee2-3835-4710-b789-6a6af46ac6ab.png)

**Comment by yasirkula** [comment]
Does the error show up in Unity's console, as well? If not, try **Edit-Preferences-External Tools-Regenerate project files**.

**Comment by BielBG** [comment]
Well, nothing shows up in the Console unless I save that code. Then it'll say the class doesn't exist. Gonna try what you commented.

**Comment by BielBG** [comment]
Yep, that worked. Thank you very much!
