### ISSUE TITLE
Cannot find instagram app when sharing

### ISSUE THREAD

**Issue by anhnguyenvn** [yasirkula/UnityNativeShare#14]
Hello,

I used plugin to share the screenshot but I couldnt see the instagram app in the list. My phone has the instagram app installed.
Could you help me on this issue? Thank you so much

Anh

**Comment by yasirkula** [comment]
Is it Android or iOS?

**Comment by anhnguyenvn** [comment]
it is on iOS only. I share one image only and also set text and subject. Thank you!

**Comment by yasirkula** [comment]
See: https://medium.com/@ihsuanlee3/instagram-icon-is-missing-from-uiactivityviewcontroller-290d9080587c

**Comment by anhnguyenvn** [comment]
Sorry, i couldn't get your point. You mean have to share multiple images?

**Comment by anhnguyenvn** [comment]
I got it, sharing only image is allowed. Thank you so much!
