### ISSUE TITLE
Auto-fill "To"

### ISSUE THREAD

**Issue by AirOwlin** [yasirkula/UnityNativeShare#140]
**Hi, dear yasirkula!**

Is it possible to add an auto-fill function to "To"?

**Comment by yasirkula** [comment]
On Android, it's said to be possible but on iOS, it isn't. I may add this feature on Android but probably not very soon.

**Comment by AirOwlin** [comment]
Thanks for the feedback. I will be waiting for the next updates. )

**Comment by yasirkula** [comment]
Does replacing _NativeShare.aar_ with the one inside [this zip archive](https://github.com/yasirkula/UnityNativeShare/files/8552430/NativeShare.zip) auto populate the recipients with `test1@gmail.com` and `test2@gmail.com` in all combinations on Android (e.g. when only text is shared, only image is shared, both text and image are shared)?

**Comment by AirOwlin** [comment]
Replaced Native Share.arr. Checked with text and image. Everything works.

**Comment by yasirkula** [comment]
Can you also check if this change affects the list of available apps in the share sheet by switching between this NativeShare version and the latest released NativeShare version? If adding recipients removes e.g. WhatsApp or Facebook from the list, it might be a problem.

**Comment by AirOwlin** [comment]
I've checked everything. When I used Gmail (and also other mail applications), it fills in all the recipients that you have recorded. The rest of the applications offer to choose from a list of friends and etc. 
Therefore, autofill doesn't break on applications such as Whatsapp or Facebook.

**Comment by yasirkula** [comment]
Thank you! I'll add this API to Android in the next release 😺

**Comment by AirOwlin** [comment]
Thank you! I will be waiting for this API. You're the best!!!
