### ISSUE TITLE
Posting image+text on Instagram 

### ISSUE THREAD

**Issue by hippogamesunity** [yasirkula/UnityNativeShare#156]
Hello! Can you confirm that only image can be shared on Instagram on Android currently (with no text)?
It looks like it works fine on iOS (image + text, but I wonder why), but on Android it ignores text.

If so, maybe you could advise other plugins that can do this? Or other possible workarounds?

I've found this asset, but I don't know if it works for image + text.
https://assetstore.unity.com/packages/tools/integration/instagram-share-kit-for-android-162237#description

**Comment by hippogamesunity** [comment]
Also found this https://stackoverflow.com/questions/32640765/sharing-text-with-image-to-instagram-using-android-intent

**Comment by yasirkula** [comment]
I've heard about this issue before, so I agree that this issue exists on Instagram (though I'm also surprised to hear that iOS works fine). If Instagram doesn't accept the standardized method of passing text to shared data (Intent.EXTRA_TEXT), I don't think we can do anything other than using their own SDK (if exists). I haven't done research about this topic so I unfortunately can't redirect you to another plugin :(

**Comment by hippogamesunity** [comment]
Ok, thanks anyway!
