### ISSUE TITLE
NativeShare.Share() throwing exception on Android prod builds only (Unity NativeShare not doing anything on Android prod builds)

### ISSUE THREAD

**Issue by dginovker** [yasirkula/UnityNativeShare#162]
**Description of the bug**

Hello! Thanks for the package.

I've got an app using NativeShare and it works great both on `development` builds and all iOS builds. Unfortunately, on Android prod I'm getting the following exception:

```
UnityEngine.AndroidJavaException: java.lang.NullPointerException: Expected to unbox a 'boolean' primative type but was returned null at
UnityEngine.AndroidJNISafe.CheckException()
AndroidJNISafe.CallStaticVoidMethod
UnityEngine.AndroidJavaObject._CallStatic 
UnityNativeShare.cs
```
From this line here: https://github.com/yasirkula/UnityNativeShare/blob/master/Plugins/NativeShare/NativeShare.cs#L208

**Reproduction steps**

Very confused, here's what I'm doing

```C#
new NativeShare()
.SetSubject("Hi!")
.SetUrl("Wee")
.SetCallback((result, _) =>
{
  switch (result)
  {
    // Stuff that works on iOS and Android development builds
  }
}).Share();
```

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2021.3.9f1
- Platform: Compiled on both Linux and Mac
- Device: Android, tested multiple devices
- How did you download the plugin: Latest .unitypackage

**Additional info**

It was hard to figure out even an exception was being thrown but I'm mostly making this to keep track of my thoughts as I debug it

**Comment by yasirkula** [comment]
Hi! Is there a C# script called UnityNativeShare.cs in your project?

**Comment by dginovker** [comment]
Yup! I'm confused too. It seems like the boolean is further inside the `AJC.CallStatic`'s stacktrace.

**Comment by yasirkula** [comment]
Can I see the full stacktrace? Is there a C# script called UnityNativeShare.cs in your project?

**Comment by dginovker** [comment]
I can't get the full stacktrace, I've been printing it out via a message dialog in my app since it isn't appearing in the logs lol.


I do not have a `UnityNativeShare.cs` in my project. Should I?

**Comment by dginovker** [comment]
Going to see if I can get the actual logs :+1:

**Comment by dginovker** [comment]
Looks like we have additional proguard/obfuscation at play. Will keep digging into it and post an update later, thanks for all your help as of now @yasirkula 


```
I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
I Unity   : UnityEngine.EventSystems.StandaloneInputModule:Process()
I Unity   : 
E Unity   : Exception: No such proxy method: GOPHNOOANPB.HasManagedCallback()
E Unity   : 
E Unity   : 
E Unity   : UnityEngine.AndroidJavaException: java.lang.NullPointerException: Expected to unbox a 'boolean' primitive type but was returned null
E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
E Unity   :   at UnityEngine.AndroidJavaObject._CallStatic (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0 
E Unity   :   at DuckyShare.OnShareClick () [0x00000] in <00000000000000000000000000000000>:0 
```

**Comment by yasirkula** [comment]
Ah, looks like it yeah. Good catch 😃

**Comment by dginovker** [comment]
Solution is to add `NativeShareNamespace.NSShareResultCallbackAndroid` to the SkipClasses of the Beebyte `ObfuscatorOptions.asset` object
