### ISSUE TITLE
share file to slack in ios

### ISSUE THREAD

**Issue by choigawoon** [yasirkula/UnityNativeShare#165]
**Description of the bug**

try to share video file to slack in ios, but only send message.
other target apps works fine. ( teams, email, sms, discord, and so on )

**Reproduction steps**

share video file to slack

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2021.3.5f1
- Platform: iOS
- Device: iPhone12-mini
- How did you download the plugin: *e.g. Asset Store, GitHub, Package Manager. Please make sure that your asset is up-to-date*

**Additional info**

Please check Logcat (Android) or Xcode console (iOS) for any meaningful error messages and include them here.

no error.

https://youtu.be/p2O_DAyU3Hk

**Comment by yasirkula** [comment]
Can be related to this FAQ:

![image](https://user-images.githubusercontent.com/10211608/220133608-e54f92ce-5a26-4436-81cb-b89ff54c4416.png)

This is also present on WhatsApp on iOS.

**Comment by choigawoon** [comment]
thank you ! it works to share either only image/video or only text on slack.
