### ISSUE TITLE
Video Share

### ISSUE THREAD

**Issue by parth521** [yasirkula/UnityNativeShare#17]
i am trying share video but how to get video path without browsing it.

**Comment by yasirkula** [comment]
If you are trying to share the video that you've just saved to gallery and if you are using NativeGallery plugin to save the video, then on Android, you can get the path of the video by calling NativeGallery.GetSavePath (change its visibility to public) before calling SaveVideoToGallery. On iOS, AFAIK, it is not possible to get the path of a video in Photos. You have to keep a separate copy of the video in e.g. Application.temporaryCachePath and share it, instead.

**Comment by parth521** [comment]
thanks
