### ISSUE TITLE
Native share not working on android

### ISSUE THREAD

**Issue by chadidi** [yasirkula/UnityNativeShare#18]
I have followed all the instruction #9  but seems not to work and also the AndroidManifest file have the provider line now after building

Do you have another fix that i can try!!
Thanks @yasirkula

**Comment by yasirkula** [comment]
What happens when you try to share something? Does the game freeze, does nothing happen or does something else happen? Can you also check Logcat logs for error messages?

**Comment by chadidi** [comment]
@yasirkula Very sorry for wasting your time there is no error, it's my fault it working fine , I was running an old build app on my phone with the same name and icon instead of the new one, where both were installed.

very sorry again and thanks for your quick response and help big up for you brother ;)
