### ISSUE TITLE
Text and subject

### ISSUE THREAD

**Issue by guidoPaglie** [yasirkula/UnityNativeShare#2]
Hi ! Your plugin works perfectly on android 7.0 thank you!

I want to change the text and subject, how can i do it using your plugin? 

In the previous version this lines were the ones which make that:

intentObject.Call<AndroidJavaObject>("putExtra", intentClass.GetStatic<string>("EXTRA_TEXT"), textToShare + shareLink);
            
intentObject.Call<AndroidJavaObject>("putExtra", intentClass.GetStatic<string>("EXTRA_SUBJECT"), ShareSubject);

Thank u in advance

**Comment by yasirkula** [comment]
I'll see what can be done about this in the weekend.

**Comment by guidoPaglie** [comment]
Thank you very much for the rapid response !
Ok ! Thank you again.

**Comment by yasirkula** [comment]
Hello again, I think I will have to edit the Android .jar library which will take some time as I don't have access to the source files right now. Then I'll also post the .jar source code for anyone who wants to extend its functionality, as well.

**Comment by yasirkula** [comment]
Can you give the latest version a try?

**Comment by guidoPaglie** [comment]
Thanks !
I am doing this:
NativeShare.Share( photoPath, "Subject", "Message" , true);

And when i try to share by whatsapp or gmail, it doesn't work.

**Comment by guidoPaglie** [comment]
It works perfect ! Thank you
