### ISSUE TITLE
Error CS0234: The type or namespace name 'Xcode' does not exist in the namespace 'UnityEditor.iOS'

### ISSUE THREAD

**Issue by programming2012** [yasirkula/UnityNativeShare#21]
Hello
      On Unity 2018.1.6f1,When Compile ，It show this error.

**Comment by yasirkula** [comment]
I've searched the error on Google but as long as iOS module is installed for Unity 2018.1.6f1, I can't see a reason for this error to pop up, sorry. As you said, it should be related to Unity itself.
