### ISSUE TITLE
ContentProvider not found

### ISSUE THREAD

**Issue by bigvanstudio** [yasirkula/UnityNativeShare#26]
I am testing the plugin on Android and when I try to share a video, noting occurs. Using the monitor app to check the console, when I try to share the video, the log shows something like "ContentProvider not found!". 

I added this AndroidManifest.xml in the Assets/Plugins directory:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.unity3d.player" xmlns:tools="http://schemas.android.com/tools" android:installLocation="preferExternal">
  <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true" />
  <application android:theme="@style/UnityThemeSelector" android:icon="@drawable/app_icon" android:label="@string/app_name">
    <activity android:name="com.unity3d.player.UnityPlayerActivity" android:label="@string/app_name">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
    </activity>
    <provider android:name="com.yasirkula.unity.UnitySSContentProvider" android:authorities="[here I put my bundle indentifier]" android:exported="false" android:grantUriPermissions="true" />
  </application>
</manifest>
```

The same message is shown in the console and the video can not be shared. I have been struggling with this all the day and I do not find the problem.. 

Any idea?

Many thanks in advance!!

**Comment by dvillaseca** [comment]
you have to define the android:authorities variable
you can find it on PlayerSettings(andoird)->other settings->packagename

**Comment by yasirkula** [comment]
You have to put AndroidManifest.xml into the Assets/Plugins/Android directory.

**Comment by AntarSoft** [comment]
Hey I'm getting the same error, even though I've set the "android:authorities" variable into a unique value which is my apk packagename

**Comment by AntarSoft** [comment]
Actually the issue is fixed, I needed to copy the Android Folder to put it directily in Plugins insteand of Plugins/NativeShare

**Comment by brijesh-brk** [comment]
There may be missplacement of Manifest.xml.
Make sure above file must be in Asset/Plugin/Android alongwith proper provider tag.

**Comment by yasirkula** [comment]
With the latest release, ContentProvider is automatically added to the AndroidManifest with a unique authorities string. So hopefully we will no longer encounter this issue.

P.S. Asset Store version isn't updated yet, only the GitHub version is up-to-date.
