### ISSUE TITLE
Choose specific app on iOS

### ISSUE THREAD

**Issue by ataylor09** [yasirkula/UnityNativeShare#27]
Is it possible to choose a specific app for sharing images/text on iOS?

Looks as if it is done [here](https://github.com/is8r/unity-SocialPostPlugin)

It is beyond my skills to figure out how they've done it, but it appears that you can post text directly to facebook and or twitter. I would like to achieve something similar but with images (and adding Instagram as an app too)

**Comment by yasirkula** [comment]
That plugin uses classes like SLServiceTypeTwitter which are deprecated in iOS 11.0, so it is not a good idea to continue using them. With NativeShare, it is not possible to share on a specific app on iOS, you have to use native SDK's for it: [Twitter](https://github.com/twitter/twitter-kit-unity/wiki), [Facebook](https://github.com/facebook/facebook-sdk-for-unity)
