### ISSUE TITLE
iOS: path for sharing

### ISSUE THREAD

**Issue by iantv** [yasirkula/UnityNativeShare#28]
Good day. I recently started working on Mac OS to develop app for iOS.
I use NativeGallery https://github.com/yasirkula/UnityNativeGallery
What path I should use when call Sharing method?

var/mobile/Containers/Data/Application/29582019-F86E-47B4-8A15-21C17940E265/Documents/MyApp/image_1.png is not work.

MyApp - the name of album.

**Comment by yasirkula** [comment]
You should use the path that NativeGallery returns in its MediaPickCallback. You can verify that the file exists via File.Exists function.
