### ISSUE TITLE
Share images on Whatsapp

### ISSUE THREAD

**Issue by mauromdq** [yasirkula/UnityNativeShare#29]
Hi, great asset!
it works perfect sharing images on Facebook, Message, Twitter... but it does not work sharing images on Whatsapp ( I need it! :).
I'm using iOS 12 and Unity 2018.2

Thanks!

**Comment by yasirkula** [comment]
Do you also include a text in your shared content or are you sharing only an image?

**Comment by mauromdq** [comment]
Yes, I’m sharing text and image together. Only on whatsapp the image doesn’t appear

**Comment by yasirkula** [comment]
Please see: https://github.com/yasirkula/UnityNativeShare/issues/12

**Comment by mauromdq** [comment]
It works perfectly!
Many thanks !!
