### ISSUE TITLE
iOS can't post subject/message

### ISSUE THREAD

**Issue by GrandAndrew** [yasirkula/UnityNativeShare#3]
iOS native sharing feature only successfully post images without the subjects/messages.

**Comment by yasirkula** [comment]
Hello GrandAndrew,

With which application did you try to share the images with? Also, what happened when you tried to post images with the subjects and/or messages?

**Comment by GrandAndrew** [comment]
Any applications, Facebook, Twitter, LINE, all have the images but no text for subject and/or message. I tried other plugin (showSocialSharing) and both the image sharing and text sharing actually works.

**Comment by yasirkula** [comment]
Months later, I've updated the plugin. While doing so, I've inspected the showSocialSharing code and frankly, I couldn't spot any significant difference between the two codes.

It may be possible that [the Facebook app itself omits the text](https://stackoverflow.com/a/29891228/2373034). I've tried Twitter with the latest update and sharing image with text worked without a problem.
