### ISSUE TITLE
iOS Instagram - not able to share

### ISSUE THREAD

**Issue by mkharibalaji** [yasirkula/UnityNativeShare#31]
Hi @yasirkula ,
        The Plugin is so cool. I am not able to share in Instagram and not even showing Instagram app in sharing apps in ios.Is it a bug ?

**Comment by yasirkula** [comment]
Instagram may not be available when sharing an image with a text. Try sharing without a text.

**Comment by mkharibalaji** [comment]
It worked !! Thanks @yasirkula
