### ISSUE TITLE
Share directly on Instagram Feed 

### ISSUE THREAD

**Issue by ziad10a** [yasirkula/UnityNativeShare#35]
Hey,

Thanks for the great open-source plugin, it works just fine.
I have this requirement where I need to share an image or a video directly unto the instagram feed.
Choosing a targer "Instagram" works fine but I get the choice to pick between "Feed or Stories" but I need to post directly into the Feed.

Anyway I can pass a custom string to make that happen ?

**Comment by yasirkula** [comment]
Unfortunately not. NativeShare just presents the shared content to the shared application, the rest is up to that application.

**Comment by yasirkula** [comment]
Hmm, if you can find the full name of the Feed share activity, and if it is consistent across different versions of the Instagram app, you may be able to use the SetTarget function.

**Comment by Russel1** [comment]
@ziad10a Did you manage to share directly to Instagram Feed? I'm looking for a way to directly share a video to Instagram.
https://developers.facebook.com/docs/instagram/sharing-to-stories/

**Comment by ziad10a** [comment]
> @ziad10a Did you manage to share directly to Instagram Feed? I'm looking for a way to directly share a video to story.
> https://developers.facebook.com/docs/instagram/sharing-to-stories/

Hey Russel I started to work with it but I got busy with work and other things so, to answer your question is haven't fully finished it.

When I do it I'll post it in here

**Comment by Russel1** [comment]
@ziad10a thank you.
