### ISSUE TITLE
[QUESTION]: how can I share an AudioClip in Android?

### ISSUE THREAD

**Issue by soypaduano** [yasirkula/UnityNativeShare#39]

**Comment by yasirkula** [comment]
You need to convert the AudioClip to a sound file. Try searching for "unity audio clip to wav" or "unity audio clip to mp3".

**Comment by soypaduano** [comment]
thanks m8

**Comment by soypaduano** [comment]
btw, it does work for FB messenger but not for whatsapp. When it sends the audio it says was a error, but the file is on whatsapp (like it can uploaded and send it).

**Comment by yasirkula** [comment]
How did you convert the AudioClip to a sound file? When you try sharing an existing audio file on the storage, what happens?
