### ISSUE TITLE
Skipping share sheet and going straight to text or FB Messenger

### ISSUE THREAD

**Issue by tommygwu** [yasirkula/UnityNativeShare#41]
We're finding that we're losing 90% of our shares because the users cancel when they get to the share sheet screen: https://screencast.com/t/FUPkyrq4u

Question: Is there a way to skip that share sheet entirely and either bring up the text message composer OR FB Messenger?

**Comment by yasirkula** [comment]
It is not possible but see this topic for a possible workaround: https://forum.unity.com/threads/native-share-for-android-ios-open-source.519865/page-2#post-3575891
