### ISSUE TITLE
No text when posting to Viber

### ISSUE THREAD

**Issue by tttestuser23** [yasirkula/UnityNativeShare#42]
Code:
```
new NativeShare().AddFile(_file).SetText(_text).Share();
```

No text when posting to Viber

**Comment by yasirkula** [comment]
Some other apps may also omit either the text or the image when both are shared together. NativeShare uses standard sharing APIs on both platforms (ACTION_SEND intent on Android and UIActivityViewController on iOS), the rest is up to the target applications: they decide which shared content to ignore or to accept.
