### ISSUE TITLE
Problem with sharing on android

### ISSUE THREAD

**Issue by kelvinwop** [yasirkula/UnityNativeShare#47]
Hello,

my app generates a csv file to be shared:
![image](https://user-images.githubusercontent.com/30770221/62091177-4f99c880-b235-11e9-9763-8561f014783a.png)
![image](https://user-images.githubusercontent.com/30770221/62091186-558fa980-b235-11e9-97d3-535c3e731b11.png)

but when I share it using:
![image](https://user-images.githubusercontent.com/30770221/62091215-67714c80-b235-11e9-8c3e-373aeb73eb04.png)

Nothing happens. No errors.

My android manifest:
![image](https://user-images.githubusercontent.com/30770221/62091243-8d96ec80-b235-11e9-9b51-1f1826f87db2.png)

**Comment by yasirkula** [comment]
Try moving the `provider` to above the `</application>` line.

**Comment by kelvinwop** [comment]
ah yes that seems to have fixed it
