### ISSUE TITLE
iOS issues or unsupported?

### ISSUE THREAD

**Issue by onsterion** [yasirkula/UnityNativeShare#48]
Hi,

I'm trying to share text and image in iOS (iphone 6s) but some options works and others not example: instagram works text + image, instagram works text + image but whatsapp only show text.

In Android Whatsapp works Fine.

This is a bug or a limitation?

Regards.-

**Comment by yasirkula** [comment]
It is a limitation. From the [FAQ](https://github.com/yasirkula/UnityNativeShare#faq):

> It is just not possible to share an image/file with text/subject on some apps (e.g. Facebook), they intentionally omit either the image or the text from the shared content. These apps require you to use their own SDKs for complex share actions. For best compatibility, I'd recommend you to share either only image or only text.

I'm kinda surprised to see that WhatsApp is preferring text over image but I'm afraid it is out of my control. I simply tell the OS to share some stuff (using ACTION_SEND on Android and UIActivityViewController on iOS), then OS handles the rest.
