### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by dqh147258** [yasirkula/UnityNativeShare#49]
Hi yasirkula,

    Thanks for your plugin , it is useful , actually you could do it more perfect I think.

You could add code to the AndroidManifest in your aar like this
``` xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="YOUR_AAR_PACKAGE_NAME" >
    <application>
        <provider
               android:name="com.yasirkula.unity.UnitySSContentProvider"
               android:authorities="${applicationId}.UnitySSContentProvider"
               android:exported="false"
               android:grantUriPermissions="true" />
    </application>
</manifest>
```

The AndroidManifest would be merge to the main AndroidManifest , and the provider would get a unique authorities followed the applicationId

**Comment by yasirkula** [comment]
Does this work with the deprecated Internal build system or only the Gradle build system?

**Comment by dqh147258** [comment]
Both build systems are supported , you can verify it by apktools.

**Comment by yasirkula** [comment]
That's interesting. Will definitely check it out. Thanks!

**Comment by yasirkula** [comment]
I've applied this technique to the latest releases of NativeShare and NativeCamera plugins. Your help is much appreciated!
