### ISSUE TITLE
Add Callback

### ISSUE THREAD

**Issue by guidoPaglie** [yasirkula/UnityNativeShare#5]
Hi, me again!

I don't know if it's possible, but maybe you know how, could you add a callback when the user finishes sharing ? 

Thank you in advance

**Comment by guidoPaglie** [comment]
Hi, sorry to bother again, could you check this please?

**Comment by yasirkula** [comment]
Hi there,

Sorry for not answering your question sooner. I've searched whether or not it is possible to receive callbacks on Android and iOS. [This thread](https://stackoverflow.com/questions/39592971/how-to-get-share-intent-callback-result) suggests that on Android, it is not possible to receive a callback. On iOS, it might be possible to receive a callback but it seems like it will require a considerable amount of effort to implement it.

I would rather not implement this feature as it will neither be a multi-platform solution nor be easy(ish) to implement. Can't you, instead, show a pause screen when the user clicks the share button?

**Comment by guidoPaglie** [comment]
Hi ! Thank you very much for you answer and research. 
Yes, i will have to do a walkaround, but it's ok, it won't be that difficult.

Thank you very much again for everythings, cheers!
