### ISSUE TITLE
"Make and manage phone calls" permission appears on Android

### ISSUE THREAD

**Issue by Mythique** [yasirkula/UnityNativeShare#50]
It didn't happen before version 1.1.5. Now on launch it asks for this permission: 
![image](https://user-images.githubusercontent.com/4488088/66431654-635a6b80-e9ea-11e9-8907-150b9d243984.png)

**Comment by yasirkula** [comment]
I must add a dummy minSdkVersion in my manifest, you are right.

**Comment by yasirkula** [comment]
Fixed in https://github.com/yasirkula/UnityNativeShare/commit/adb30521ac7ed0d0fecad643efbfe2bdd70ea6db
