### ISSUE TITLE
Android Manifest <Provider> Tag

### ISSUE THREAD

**Issue by iliyasmd** [yasirkula/UnityNativeShare#51]
Hi Yasir,

Thanks for your great plugin.
I think you have updated your plugin for Android.
The <Provider> Tag is not appearing in AndroidManifest.xml in Temp/StagingArea. 
It will be great if you fix so I can continue using in my upcoming games

regards
iliyas

**Comment by yasirkula** [comment]
I've renamed com.yasirkula.unity.UnitySSContentProvider as com.yasirkula.unity.NativeShareContentProvider. If NativeShareContentProvider exists in the generated AndroidManifest, then there should be no issues. If it doesn't, which Unity version are you using and which build system (Internal, Gradle) is currently enabled?

**Comment by iliyasmd** [comment]
No NativeShareContentProvider is not generated. I'm using Unity 2019.2.8f1. I can't find where to change the Build System. PFA screenshot. Kindly help.
![Untitled-1](https://user-images.githubusercontent.com/56373649/66619396-6b88f580-ebfa-11e9-9751-44fd36e634aa.png)
.

**Comment by iliyasmd** [comment]
Thanks, Yasir,

Its working fine after updating your plugin from Asset Store.
