### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by Pankti16** [yasirkula/UnityNativeShare#52]
Hello,
I am trying to share a video on social media using Native Share, the following is the code I used:
```
Debug.Log(videoPath);
        new NativeShare().AddFile(videoPath).SetSubject(shareSubject).SetText(shareText).Share();
```

It gave me ```File does not exist at path or permission denied: file:///storage/emulated/0/MyFolder/myVideo.mp4```
Permissions for read and write external storage is granted. The file also exists at the path.

**Comment by yasirkula** [comment]
The issue is resolved I'm assuming?

**Comment by Pankti16** [comment]
It is resolved
Thanks

**Comment by Pankti16** [comment]
Hello,

How can I show a list of images from a folder using the Native Gallery
plugin?
I just want to display them.

-- 
Thanks & Regards
Pankti Shah
Developer & Designer

**Comment by yasirkula** [comment]
It is not possible to display only a subset of the Gallery with NativeGallery, sorry.

**Comment by Pankti16** [comment]
Thanks for your response.
