### ISSUE TITLE
Deeplink support?

### ISSUE THREAD

**Issue by flashmandv** [yasirkula/UnityNativeShare#54]
Hello,

Thank you for your great and free plugin.
However I'm trying to implement game room invite for our game using deep linking, but i'm not sure if UnityNativeShare supports this.
I need to pass a parameter (room number) to our website links and somehow read the value from the opened Unity game.
Can you suggest free and simple solution to read deep link parameters in Unity?

Thanks

**Comment by yasirkula** [comment]
I'm not planning to add deeplink support for the time being. Googling "unity deeplink" yielded these repositories, they might be helpful:

https://github.com/TROPHiT/UnityDeeplinks
https://github.com/BranchMetrics/unity-branch-deep-linking-attribution

**Comment by flashmandv** [comment]
Thanks. I'm integrating the TROPHiT/UnityDeeplinks solution. it is the simplest
