### ISSUE TITLE
Build error: duplicate com.yasirkula.unity.NativeCameraContentProvider

### ISSUE THREAD

**Issue by hansg60** [yasirkula/UnityNativeShare#55]
Hello,
I have both NativeCamera and NativeGallery in my project.  I am getting a build error when building for android.

I have updated the NativeCamera and NativeGallery to the latest versions.

Thank you for your help.

Here is my AndroidManifest.xml

`<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns:amazon="http://schemas.amazon.com/apk/res/android" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" package="com.unity3d.player" android:installLocation="preferExternal" android:versionCode="1" android:versionName="1.0">
   <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true" />
   <application android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:icon="@drawable/app_icon" android:label="@string/app_name" android:debuggable="true">
      <activity android:name="com.unity3d.player.UnityPlayerActivity" android:label="@string/app_name" android:hardwareAccelerated="true">
         <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
         </intent-filter>
         <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
      </activity>
      
      <provider android:name="com.yasirkula.unity.NativeCameraContentProvider" android:authorities="com.wingboat.AllowanceBot" android:exported="false" android:grantUriPermissions="true" />
   </application>
   <uses-permission android:name="android.permission.INTERNET" />
</manifest>`

Here is the error message:

`CommandInvokationFailure: Gradle build failed. 
/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -classpath "/Applications/Unity/Hub/Editor/2019.3.0b7/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-5.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "bundleRelease"

stderr[
/Users/hans/WingBoat/AllowanceBotUnity/AllowanceBotUnity/Temp/gradleOut/launcher/src/main/AndroidManifest.xml:65:13-60 Error:
	Attribute provider#com.yasirkula.unity.NativeCameraContentProvider@authorities value=(com.wingboat.AllowanceBot) from [:unityLibrary] AndroidManifest.xml:65:13-60
	is also present at [:NativeCamera:] AndroidManifest.xml:6:5-71 value=(com.wingboat.AllowanceBot.NativeCameraContentProvider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:63:9-67:50 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processReleaseManifest'.
> Manifest merger failed : Attribute provider#com.yasirkula.unity.NativeCameraContentProvider@authorities value=(com.wingboat.AllowanceBot) from [:unityLibrary] AndroidManifest.xml:65:13-60
  	is also present at [:NativeCamera:] AndroidManifest.xml:6:5-71 value=(com.wingboat.AllowanceBot.NativeCameraContentProvider).
  	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:63:9-67:50 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org`

**Comment by yasirkula** [comment]
NativeCamera automatically adds the provider to the AndroidManifest, so you should remove the provider you have in your AndroidManifest.xml.

**Comment by hansg60** [comment]
The one in there is the one added by NativeCamera.  I tried removing it,
but your code added it back in.

**Comment by yasirkula** [comment]
Does the string "com.wingboat.AllowanceBot.NativeCameraContentProvider" appear anywhere in your project? You can use CTRL+Shift+F to search the Entire Solution on Visual Studio.

**Comment by hansg60** [comment]
Hello,

No, that string does not appear, but I found another manifest file in a temp directory that was causing the problem.

Thanks for your help,
Hans
