### ISSUE TITLE
Plugin not working on Xiaomi devices in landscape mode

### ISSUE THREAD

**Issue by play123** [yasirkula/UnityNativeShare#56]
Hi,
This plugin not working on android 9 or up.
I'm using unity 18.3. it's work in android 8.
It's not showing app list. It's showing share with other devices.im attached image. Please help.

![Uploading Screenshot_2019-11-30-21-48-38-172_android.jpg…]()

Best regards,
Anil Solanki

**Comment by yasirkula** [comment]
Can you reupload the image? It can't be loaded on my side. Also check out logcat for any meaningful error messages so that I might be able to pinpoint the issue.

**Comment by play123** [comment]
HI, 
sorry for the delay. I'm uploading the image again please check.
![Screenshot_2019-11-30-21-48-52-701_android](https://user-images.githubusercontent.com/5018394/69940162-89424f00-1507-11ea-89ba-3a55e49cd66d.jpg)

**Comment by yasirkula** [comment]
It is the first time I'm seeing this share sheet UI, actually.

- Please check logcat for any meaningful error messages
- Try entering "**image/jpeg**" to AddFile's **mime** parameter

**Comment by play123** [comment]
HI,
Here is I get from logcat

12-04 18:08:54.638  2067  2094 W ActivityManager: Ignoring remove of inactive process: ProcessRecord{c4ecfdc 0:com.google.process.gservices/u0a19}
12-04 18:09:16.469  2067  2089 I ActivityManager: Process com.google.process.gservices (pid 14857) has died: cch+6CEM
12-04 18:09:16.625  2067 10551 I ActivityManager: START u0 {act=android.intent.action.CHOOSER cmp=android/com.android.internal.app.ChooserActivity (has extras)} from uid 10291
12-04 18:09:16.649 13439 13439 I Unity   : onPause
12-04 18:09:16.974 13439 13458 D Unity   : Sensor :        Accelerometer ( 1) ; 0.001190 / 0.00s ; ICM20607 Accelerometer / InvenSense
12-04 18:09:17.045  2067  2096 I ActivityManager: Start proc 15097:android:ui/1000 for activity android/com.android.internal.app.ChooserActivity caller=com.d.design
12-04 18:09:17.112 13439 13439 I Unity   : windowFocusChanged: false
12-04 18:09:18.153  2067  2102 I ActivityManager: Displayed android/com.android.internal.app.ChooserActivity: +1s138ms


HERE IS MY CODE

  public void StartSharing(List<string>Files)
    {
        NativeShare share =   new NativeShare();

        share.SetSubject("D-Design");
        share.SetText("D-Design file share");
        share.SetTitle("D-Design file share");
       

        for (int i = 0; i < Files.Count; i++)
        {
            string fileName = Files[i].Replace("\\", "/");
            string mineType = "image/jpeg";

            if (fileName.ToLower().Contains(".mp4"))
            {
                mineType = "video/mp4";
            }

            share.AddFile(fileName, mineType);
        }

        share.Share();      
    }

**Comment by yasirkula** [comment]
Hmm, try replacing fileName with System.IO.Path.GetAbsolutePath(fileName) in AddFile. If that doesn't work, I won't be able to pinpoint this issue since there are no error messages in logcat either. I'd recommend you to also try out the example code and see if you can share screenshots properly: https://github.com/yasirkula/UnityNativeShare/#example-code

**Comment by play123** [comment]
HI,
Thanks for your quick replay. this issue is reproduced in MI Note 5 pro. other devices I check its work fine. thanks for your quick support.

best regards,
Anil Solanki

**Comment by yasirkula** [comment]
I'm assuming that the example code didn't work on MI Note 5 Pro either, am I correct?

**Comment by play123** [comment]
Yes, this is not working but I deeply investigate then I found this.
01_When I Use facebook. And Click on sharing then I got this share window.

![Screenshot_2019-12-06-11-56-11-447_android](https://user-images.githubusercontent.com/5018394/70306620-59f45080-182d-11ea-936b-64fa73b527c1.jpg)


And when I use your plugin then  I got this share window.

![Screenshot_2019-12-06-11-58-19-264_android](https://user-images.githubusercontent.com/5018394/70306668-742e2e80-182d-11ea-87d4-237c9512ecdf.jpg)


 Issue: May Be I think the window does not open fullscreen this an issue.  if this helps you. Also, you can close this issue because this is an I think device-specific issue.

Best regards,
Anil Solanki

**Comment by yasirkula** [comment]
Thanks for all the info! I can't promise any solutions at the moment because I still don't know what might be causing this issue but will update the plugin if I find a fix. The Issue should stay open in the meantime.

**Comment by yasirkula** [comment]
P.S. Does removing these lines affect the outcome:

```csharp
share.SetSubject("D-Design");
share.SetText("D-Design file share");
share.SetTitle("D-Design file share");
```

**Comment by yasirkula** [comment]
**Update:** It is reported that this issue occurs in landscape mode only.

**Comment by Nullnill** [comment]
Hello Yasirkula, 

any updates to this issue since January? 
I seem to run into the same thing with landscape mode on Samsung S9+

Regards.

**Comment by yasirkula** [comment]
Sadly not. I don't know the cause of the issue. Maybe [other solutions](https://assetstore.unity.com/packages/tools/integration/natshare-mobile-sharing-api-117705) don't suffer from this issue?

**Comment by fdtdev** [comment]
I can confirm that I tested it today with https://assetstore.unity.com/packages/tools/integration/cross-platform-native-plugins-lite-version-37272 and the same happens, in a xiaomi mi 9

**Comment by Divyanshu-del** [comment]
I am facing the same issue in some devices. Is there an update or do I need to switch to another plugin?

**Comment by yasirkula** [comment]
Unfortunately, there are no updates. The only related topics I could find on the internet are these:

- http://c.mi.com/thread-2671171-1-0.html?mobile=no (I am not the author of 4th comment)
- https://www.reddit.com/r/miui/comments/dzj6qx/no_option_to_share_on_other_apps_in_landscape/

If you find a working plugin, please also let me know.

**Comment by Divyanshu-del** [comment]
> **Update:** It is reported that this issue occurs in landscape mode only.

Exactly... U right.. i performed all kinds of test and I figured the same

**Comment by yasirkula** [comment]
> Sadly not. I don't know the cause of the issue.

**Comment by vipulpatel0911** [comment]
Thanks @yasirkula  for a wonderful plugin. I think this issue is at MI level and not related with this plugin. As you can see they have removed entire section of other applications in landscape mode, might be because of space issue. Can we all unite and start bombarding on MI to solve this issue asap? 

Because @yasirkula has done a great work and this problem is not in his hand. So instead of asking a solution from him, we should ask it from MI.

Thanks.
