### ISSUE TITLE
iOS image is not appearing when sharing using WhatsApp

### ISSUE THREAD

**Issue by AlekzFateJumper** [yasirkula/UnityNativeShare#57]
Since last WhatsApp update, the image no longer appears when I share using iOS, only the text appears. In AirDrop it worked fine, but in WhatsApp the image gets lost.

**Comment by yasirkula** [comment]
Unfortunately, it is never reliable to share image+text. For example, Facebook omits the text but some apps may decide to omit the image instead. I hope WhatsApp will resolve this issue on the next update but I'd recommend you to share only image or only text.
