### ISSUE TITLE
Unable to merge android manifests. See the Console for more details. 

### ISSUE THREAD

**Issue by thucungcuatoi** [yasirkula/UnityNativeShare#58]
Hi,
I have 2 errror about Unable to merge android manifests. See the Console for more details.
Can you help me about it?

------ Error #1 ---------
Error: [Temp\StagingArea\AndroidManifest-main.xml:11, E:\Unity Games\FlappyBirds_2019\Temp\StagingArea\android-libraries\NativeShare\AndroidManifest.xml:3] Trying to merge incompatible /manifest/application/provider[@name=com.yasirkula.unity.NativeShareContentProvider] element:

UnityEditor.HostView:OnGUI()

------ Error #2  ---------
CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:/Program Files/Java/jdk1.8.0_211\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/Cuong/AppData/Local/Android/Sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Hub\Editor\5.6.7f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml:11, E:\Unity Games\FlappyBirds_2019\Temp\StagingArea\android-libraries\NativeShare\AndroidManifest.xml:3] Trying to merge incompatible /manifest/application/provider[@name=com.yasirkula.unity.NativeShareContentProvider] element:
  <provider
--    @android:authorities="com.thucungcuatoi.flappybirds"
  <provider
++    @android:authorities="${applicationId}.NativeShareContentProvider"
]
stdout[

]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.HostView:OnGUI()

------ AndroidManifest.xml  ---------
<provider
			  android:name="com.yasirkula.unity.NativeShareContentProvider"
			  android:authorities="com.thucungcuatoi.flappybirds"
			  android:exported="false"
			  android:grantUriPermissions="true" />

**Comment by yasirkula** [comment]
You should remove NativeShare's <provider> from your AndroidManifest.xml, it is now added automatically.
