### ISSUE TITLE
Exclude Facebook 

### ISSUE THREAD

**Issue by svisveswar001** [yasirkula/UnityNativeShare#59]
How would I exclude Facebook App from the Chooser on Android. 
(For IOS I was able to do add this to NativeShare.mm
activity.excludedActivityTypes = @[UIActivityTypePostToFacebook];

For Android I see there is an option to EXTRA_EXCLUDE_COMPONENTS but don't know how it can be set. Any suggestions?

**Comment by yasirkula** [comment]
NativeShare doesn't support it. You'd have to modify the Android source code on Android Studio, rebuild the NativeShare.aar file and replace the one in your Unity project with it.

**Comment by svisveswar001** [comment]
Ok thank you!
