### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Tivoyagefeak** [yasirkula/UnityNativeShare#61]
Thanks for the great plugin. Its really easy to use! The Plugin works on my Pixel 2 as intended. But there is an error message in the Logcat:
`
 02.24 11:11:06.487 25071 25190 Error DatabaseUtils: Writing exception to parcel
02.24 11:11:06.487 25071 25190 Error DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.yasirkula.unity.NativeShareContentProvider uri content://com.client.appname.NativeShareContentProvider/devroot/storage/emulated/0/Android/data/com.client.appname/files/images/screenshot.png from pid=21818, uid=1000 requires the provider be exported, or grantUriPermission()
02.24 11:11:06.487 25071 25190 Error DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
02.24 11:11:06.487 25071 25190 Error DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
02.24 11:11:06.487 25071 25190 Error DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:593)
02.24 11:11:06.487 25071 25190 Error DatabaseUtils: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:507)
02.24 11:11:06.487 25071 25190 Error DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:307)
02.24 11:11:06.487 25071 25190 Error DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
02.24 11:11:06.487 25071 25190 Error DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:994)
`

In the AndroidManifest from the final apk everything looks fine. The provider looks normal:
`        <provider
            android:name="com.yasirkula.unity.NativeShareContentProvider"
            android:exported="false"
            android:authorities="com.client.appname.NativeShareContentProvider"
            android:grantUriPermissions="true" />`
I tried to set SkipPermissionsDialog to false with a custom Manifestfile with no effect on the error message. Is it a normal behaviour?

**Comment by yasirkula** [comment]
The plugin still works fine despite this error, did I understand correctly?

**Comment by Tivoyagefeak** [comment]
Yeah the popup with the selection of shareable apps appears and I can share image + text (tried with WhatsApp)
Once in a while my phone goes directly into the locked mode in the same time the selection view apears.. If I unlock it again everthing is fine. I was wondering if this could have something to do with the error.

**Comment by yasirkula** [comment]
I've applied the suggested fix, feel free to give it a shot by replacing NativeShare.aar with the one inside this zip archive: [NativeShare.zip](https://github.com/yasirkula/UnityNativeShare/files/4246351/NativeShare.zip)

**Comment by Tivoyagefeak** [comment]
Thanks! I'll try it on thursday.Am 24.02.2020 20:14 schrieb Süleyman Yasir KULA <notifications@github.com>:I've applied the suggested fix, feel free to give it a shot by replacing NativeShare.aar with the one inside this zip archive: NativeShare.zip

**Comment by Tivoyagefeak** [comment]
Hey sorry for the late update on this.
I tried the new plugin and still get the same Error. But everything works find so I just ignore it ;-)
