### ISSUE TITLE
Problems to share links on Facebook

### ISSUE THREAD

**Issue by andrewmautone** [yasirkula/UnityNativeShare#64]
Hello, first of all ,Thanks for the asset.
I tried to share a link on facebook but it dosn't appear, it only appear the image.I know that text can't be shared on facebook, but i was tring to share only the link.
Thanks.

**Comment by andrewmautone** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/13738007/76560741-9cf33f00-6480-11ea-8c28-da7b86b2d4e8.png)

**Comment by yasirkula** [comment]
Links are also considered text, so you can't share an image with a link.

**Comment by andrewmautone** [comment]
Can I share only the link ?

**Comment by yasirkula** [comment]
Yes, it should be possible.
