### ISSUE TITLE
Can't share my own image

### ISSUE THREAD

**Issue by Eloren1** [yasirkula/UnityNativeShare#65]
I don't want to take a screenshot, how can I share my own banner.png? Where should I place it? 

`new NativeShare().AddFile("\\banner.png").SetSubject("Subject goes here").SetText("Download this game!").Share();`

It doesn't work

**Comment by yasirkula** [comment]
Where is this file located at?

**Comment by Eloren1** [comment]
I can place this banner everywhere

**Comment by yasirkula** [comment]
You should place/save it to Application.temporaryCachePath and put its filepath to AddFile.

**Comment by Eloren1** [comment]
I don't know how to do this... I thought I need just put my banner.png to Assets\Sprites\Share and set this path

**Comment by yasirkula** [comment]
You can change the file's extension to _.bytes_, assign it to a public _TextAsset_ variable, and then call _File.WriteAllBytes_ with the TextAsset's _bytes_ property to create a file using it.
