### ISSUE TITLE
can't build on android console errors

### ISSUE THREAD

**Issue by GameDevBhavesh** [yasirkula/UnityNativeShare#68]
![errors](https://user-images.githubusercontent.com/38570988/78674876-e446e100-7901-11ea-8baf-aa02518024ab.PNG)

**Comment by yasirkula** [comment]
Are there any NativeShare.jar files in the project? If not, how many NativeShare.aar files are there? If more than one, at which locations?

**Comment by GameDevBhavesh** [comment]
i'm also using gree's native webview plugin for unity and it cointains  webview.jar file and there is only 
 one nativeshare.aar file

**Comment by GameDevBhavesh** [comment]
and also under gree's plugin there is one .jslib file

**Comment by yasirkula** [comment]
You need only Plugins folder, yes. If deleting other NativeShare files doesn't resolve the issue, then it'd be helpful to see the whole error message; it might indicate where the duplicate classes are located at.

**Comment by GameDevBhavesh** [comment]
> You need only Plugins folder, yes. If deleting other NativeShare files doesn't resolve the issue, then it'd be helpful to see the whole error message; it might indicate where the duplicate classes are located at.

thanks man your great its builded without any errors and working as i wanted thanks again : )
