### ISSUE TITLE
Unable to load image - Instagram Feed Share Problem - Android

### ISSUE THREAD

**Issue by sepehr777** [yasirkula/UnityNativeShare#70]
Hi,
I just used the example code and remove all the subject and text parts, only image file remain, but when I try to share my screenshot in Instagram feed, I'll get the "Unable To LoadImage" error.
All other share options are okay, like the Instagram story or WhatsApp.

Android Version is 8 - Phone is Huawei Nova 2 Plus - Landscape

**Comment by yasirkula** [comment]
I'm suspecting that this is an issue with the Instagram app itself, since other developers are also facing a similar issue. I'm following this SO entry to get updates on the issue: https://stackoverflow.com/questions/60776730/instagram-android-share-intent-unable-to-load-image

**Comment by sepehr777** [comment]
Thank you for your fast reply :)
The issue still stands there with the last official release, maybe it will fix with the beta version.

**Comment by sepehr777** [comment]
Can I be hopeful there will be an update to fix this issue for broken versions of instagram?

**Comment by yasirkula** [comment]
I'm not planning to release a fix, I don't know if there is a way to fix this issue on broken Instagram versions. I haven't tested SetTarget with Instagram, so I myself can't help with that but hopefully another developer can answer your question.
