### ISSUE TITLE
How To Share GIF Using this package file

### ISSUE THREAD

**Issue by Nameless77** [yasirkula/UnityNativeShare#71]
hello sir and also thanks to you for very great plugin .
all things work file but i want to know how to create gif file and share that file using "UnityNativeShare".
is there any way for create gif files and share them i shaw some plugins for that but those are quite expensive for me as a learner so can you please tell me this.
how to create gif files and share them on social medias like whats app, facebook,twitter etc.
and thank you so much bcz i tried your other plugins and those are very helpfull for me.😊😊😊😊😊.

**Comment by yasirkula** [comment]
Unfortunately, you can't record a gif animation with this plugin. You need to use a dedicated plugin for this (simply google "unity gif recorder github" and you'll find free solutions). Hope that helps!
