### ISSUE TITLE
Share link on iOS

### ISSUE THREAD

**Issue by fi4sk0** [yasirkula/UnityNativeShare#72]
Hey there @yasirkula and thanks for your assets. I just found them and they saved a ton of time for me! Keep up the good work!

Something I struggled with was to share links. I found out, that on iOS you can just send a list of objects to the share menu and depending on what kind of object they are, the menu changes. 

Since I just wanted to share a link in my app, I changed line 24 of NativeShare.mm https://github.com/yasirkula/UnityNativeShare/blob/7beb32c3b2f0b71cf8b2a158bdecc08d95c8d986/Plugins/NativeShare/iOS/NativeShare.mm#L24

to

```objc
[items addObject:[NSURL URLWithString:filePath]];
```

but maybe there could be a more general approach? Maybe something `new NativeShare().AddLink()`. I haven't tested that yet but I'll probably run into the same problem on Android. Any thoughts on that?

Cheers, 
Timo

**Comment by yasirkula** [comment]
Does `new NativeShare().SetText("INSERT_URL_HERE").Share();` not work? If it doesn't, I might have to change the code as you suggested.

**Comment by cihadturhan** [comment]
@yasirkula `setText` doesn't do the same thing because some apps use url to fetch website metada and add website image and title like below:

![image](https://user-images.githubusercontent.com/3739536/81121666-f4b99e00-8f37-11ea-9dc6-78fb221f2796.png)

Nice plugin btw, thanks for your efforts.

**Comment by yasirkula** [comment]
[AFAIK](https://forum.unity.com/threads/native-share-for-android-ios-open-source.519865/page-10#post-5753392), WhatsApp can fetch the link from the text (SetText) and show the website metadata. Which apps failed to show the website metadata when using SetText? On which platform did this happen?

**Comment by cihadturhan** [comment]
I did a quick test by adding NSURL into share items. 
Seems like current solution works except **twitter** app:

![IMG_5157](https://user-images.githubusercontent.com/3739536/81295658-6c431680-9079-11ea-9ffd-9b82271e73f2.PNG)
![IMG_5158](https://user-images.githubusercontent.com/3739536/81295684-76651500-9079-11ea-8622-1599519293c5.PNG)

I guess that's ok because it'll probably create website card after you press "tweet" button.

**Comment by yasirkula** [comment]
Thanks for the test! I also think that the current solution is OK at the moment.

**Comment by icanb** [comment]
+1, `AddLink()` method would be really nice
