### ISSUE TITLE
how to Share an Existed GIF file using native share.

### ISSUE THREAD

**Issue by Nameless77** [yasirkula/UnityNativeShare#76]
Ok i have a gif file in my storage(i found a method to capture gif files and save it to storage).
now my question is that how can i share existing gif file using nativeshare.
can you please suggest me.and thank you very much for this asset

**Comment by yasirkula** [comment]
Assuming that you know the path of the gif file, you can simply use `new NativeShare().AddFile(gifFilePath).Share();`

**Comment by Nameless77** [comment]
thank you so much it worked.
by the way i dont know that usin this plugin i can share most of the things.
thank you very much.
and i also have other problem and that is when i share something from my default messaging app(OS Default messaging app) then it showed cannot attach toast message.
so i just want to know that is there any problme with my phone or Default messaging app or is there any limitation of plugin(please dont get me wrong).
bcz i saw same problem with hill climbing racing's sharing system.
when i click on share image with default messaging then i showed me same toast.

**Comment by yasirkula** [comment]
There might be an issue with the default messaging app but I can't say for sure :/
