### ISSUE TITLE
How to Add receiver E-mail

### ISSUE THREAD

**Issue by Keshavjps28** [yasirkula/UnityNativeShare#79]
Kindly tell if any function exists for adding the receiver's Email ("TO"  field) in the Email client Automatically by clicking the sharing button and I am using SetTarget(), Or any other way I can add the receiver's E-mail other than using SMTP.

**Comment by yasirkula** [comment]
There is no built-in support for it. But it can be achieved by modifying the native source code on Android (not sure about iOS): https://forum.unity.com/threads/native-share-for-android-ios-open-source.519865/page-5#post-4431853

**Comment by Keshavjps28** [comment]
Thanks for your help!!!

**Comment by Keshavjps28** [comment]
Can I submit the PR for the same

**Comment by yasirkula** [comment]
Sure! But please follow the same coding style, use Windows file endings and [use tabs instead of spaces](https://www.youtube.com/watch?v=SsoOG6ZeyUI).
