### ISSUE TITLE
Support for callbacks? Cancel share?

### ISSUE THREAD

**Issue by TeddyMathias** [yasirkula/UnityNativeShare#8]
Hi thanks for making this plugin! I'm wondering if you've included support for callbacks for both the completion of share and when the user presses cancel? These would both be very helpful and put you well above the other share plugins out there for Unity :)

**Comment by guidoPaglie** [comment]
Hi ! 

I've posted the same some months ago, you can check the answer here

https://github.com/yasirkula/UnityNativeShare/issues/5

Hope it helps, cheers!
