### ISSUE TITLE
PDF file not attached

### ISSUE THREAD

**Issue by AliAkbarMontazeri** [yasirkula/UnityNativeShare#81]
The file is not attached. Only shows text from `SetText()` function. I'm just using a line of code from the examples here.

> public void ShareIt()
    {
        new NativeShare().AddFile(Application.streamingAssetsPath + "/" + fileName).SetSubject("Subject goes here").SetText("Hello world!").Share();
    }
When I'm building the app I got an error that says it collide with another value. So I added `tools:replace` in the AndroidManifest and it works.
Does adding `tools:replace` makes the file not attached?

**Comment by yasirkula** [comment]
On Android, you need to use WWW in a coroutine to extract files from StreamingAssetsPath. Example code: https://forum.unity.com/threads/native-share-for-android-ios-open-source.519865/page-3#post-3917233

**Comment by AliAkbarMontazeri** [comment]
Wow thanks @yasirkula ! It works! I think you should put that on wiki section
