### ISSUE TITLE
Can´t share wav file to whatsapp from an ios device.

### ISSUE THREAD

**Issue by gonzadavidov** [yasirkula/UnityNativeShare#83]
Hey there @yasirkula, I am trying to share a wav file from my app using your asset, everything works fine from an anndroid device and also sharing via email from my IOS device.
The issue comes when I try to share the file to whatsapp on IOS, the option appears and the text is sent but the file isn´t.
Thanks for your help.

**Comment by yasirkula** [comment]
What happens when you don't call SetText?

**Comment by gonzadavidov** [comment]
Thanks,
It works fine!!! so now, how can I share the file with the text also? at least in separate messages.

**Comment by gonzadavidov** [comment]
Is there a way to send the file with the text when sharing via email for example but only the file via WhatsApp?

**Comment by yasirkula** [comment]
I didn't add any app-specific logic. If you are interested in modifying the iOS source code for this task, I believe [this pull request's](https://github.com/yasirkula/UnityNativeShare/pull/75) NativeShare.mm file executes some app-specific logic.

**Comment by gonzadavidov** [comment]
Okay, Thank you very much.
