### ISSUE TITLE
 Error DatabaseUtils java.lang.SecurityException: Permission Denial

### ISSUE THREAD

**Issue by smayleee** [yasirkula/UnityNativeShare#85]
Hi, i am getting this error in android logcat when i try to share
 Error DatabaseUtils java.lang.SecurityException: Permission Denial: reading com.yasirkula.unity.NativeShareContentProvider uri content:com.packagename.com/NativeShareContentProvider/devroot/storage/emulated/0/Android/data/com.packagename.com/cache/shared%20img.png from pid=7928, uid=1000 requires the provider be exported, or grantUriPermission()

share is successful but i am worry about this..
how to fix this?

**Comment by yasirkula** [comment]
Duplicate of #61. Since sharing works successfully, I wouldn't worry about it.
