### ISSUE TITLE
Did not solve the horizontal screen problem of Xiaomi devices

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnityNativeShare#86]
After I upgraded the plug-in and confidently removed my method of judging Xiaomi devices, I repackaged the apk, and it still failed in landscape mode. haha
![image](https://user-images.githubusercontent.com/50401776/90309076-82cdf900-df17-11ea-8351-bfede750e405.png)
![image](https://user-images.githubusercontent.com/50401776/90309080-86fa1680-df17-11ea-8307-c104949ec70f.png)
This is a screenshot of my mobile phone system
My phone model is realmex. I flashed miui
I think your judgment should be the Xiaomi device or the miui system
Or can I customize whether to use the new custom layout

**Comment by ShenKang4181** [comment]
![image](https://user-images.githubusercontent.com/50401776/90309141-31723980-df18-11ea-957c-5280d89df74c.png)

**Comment by yasirkula** [comment]
I was checking for [Xiaomi](https://github.com/yasirkula/UnityNativeShare/blob/6e8c3de7fcaf1d7d23f00d09759159629a7e4804/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity/NativeShare.java#L65) but maybe I have to check for [MIUI instead](https://gist.github.com/Muyangmin/e8ec1002c930d8df3df46b306d03315d).

At the moment, you can execute the following code in Start function to resolve this issue:

```csharp
using( AndroidJavaClass ajc = new AndroidJavaClass( "com.yasirkula.unity.NativeShare" ) )
	ajc.SetStatic<bool>( "alwaysUseCustomShareDialog", true );
```

**Comment by ShenKang4181** [comment]
I have done it! love you
