### ISSUE TITLE
Low Image Resolution

### ISSUE THREAD

**Issue by yusufozcan** [yasirkula/UnityNativeShare#87]
First of all thank you for this library. It helped me too much. My problem is the shared image quality is very less than captured screen picture. I also tried `ScreenCapture.CaptureScreenshotAsTexture(4);` code to take super high res image and I checked saved image on the disk is very high quality. But it losts quality while sharing. I couldn't find where. Maybe in native code.

**Comment by yasirkula** [comment]
Social media/chat apps can compress images to reduce their sizes. NativeShare doesn't alter the input files/Textures in any way, so I'm guessing that this issue is caused by the social media/chat app.

**Comment by yusufozcan** [comment]
I also tried to save to storage but I got the same result.

**Comment by yasirkula** [comment]
You said "I checked saved image on the disk is very high quality", how does saving to storage yields the same result then?

**Comment by yasirkula** [comment]
Closed due to inactivity.
