### ISSUE TITLE
Share on ios is in English

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnityNativeShare#88]
This is the effect of sharing in the album
![image](https://user-images.githubusercontent.com/50401776/90379415-4b915080-e0ad-11ea-9984-ce7ec3a4835f.png)
This is the effect of using NativeShare
![image](https://user-images.githubusercontent.com/50401776/90379498-64016b00-e0ad-11ea-86dd-9ecafa8c398c.png)
Does the plug-in contain methods for specifying languages?

**Comment by yasirkula** [comment]
Please see: https://github.com/yasirkula/UnityNativeShare/issues/53
