### ISSUE TITLE
Callbacks!!!!!

### ISSUE THREAD

**Issue by Nameless77** [yasirkula/UnityNativeShare#89]
first of all thank you so much for providing such an amazing plugin.worked like a charm but i have a question and that is,
in my game i want to give some coins to the user for sharing my game on social media(like on whatsapp or twitter or facebook etc.)
so how can i actually know that user shared my game link on social media.so i just wanted to ask that is there any way to figure out that user share the link of my game using NativeShare. if it possible then can you please tell me and can you give me a simple code example for doing that.

**Comment by yasirkula** [comment]
Selected app may not always have a value, I assign its value only if OS provides that information. If that information is vital to you (in my opinion, it shouldn't), you can execute the following code in Start/Awake:

```csharp
using( AndroidJavaClass ajc = new AndroidJavaClass( "com.yasirkula.unity.NativeShare" ) )
	ajc.SetStatic<bool>( "alwaysUseCustomShareDialog", true );
```

Now, the share dialog will look less pretty but the Selected App is more likely to have a value.

**Comment by Nameless77** [comment]
ok that is also resolved and thank you so much for suggest me and ya share dialog become dark after apply your solution(well thats not a problem for me).so i just want to ask that will it affect share functionality in any way?

**Comment by yasirkula** [comment]
It shouldn't. If it does, it should be reported as another Issue.

**Comment by Nameless77** [comment]
ok thanks you for your awesome support.now i am closing this issue
