### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by volkerku** [yasirkula/UnityNativeShare#93]
I'm getting this error when I try to build for iOS after updteing to the new version (1.6)

Assets\Plugins\NativeGallery\NativeGallery.cs(6,7): error CS0246: The type or namespace name 'NativeGalleryNamespace' could not be found (are you missing a using directive or an assembly reference?)​

Any idea?

PS, I'm also using ScreenshotHelper Plus and NativeShare which I updated as well. Hard to tell, but I think they are related and use commong libraries, right?

**Comment by yasirkula** [comment]
You can try deleting NativeShare folder and [reimporting it from scratch](https://github.com/yasirkula/UnityNativeShare#installation).

**Comment by volkerku** [comment]
Yes tried that, but same error, Tried from asset store and the unitypackage on github.
I was deleting the  Assets/Plugins/NativeShare foldr.\er.

**Comment by volkerku** [comment]
Ok tried that. Deleted and reimported NativeGallery (and NativeShare just to make sure), but I'm stil getting the same error. Tried building iOS and Android, but no luck.

**Comment by yasirkula** [comment]
I really don't know why you are having this issue, let alone on both Android & iOS. On Android, [these classes](https://github.com/yasirkula/UnityNativeGallery/tree/master/Plugins/NativeGallery/Android) belong to NativeGalleryNamespace namespace and on iOS, [these classes](https://github.com/yasirkula/UnityNativeGallery/tree/master/Plugins/NativeGallery/iOS) belong to NativeGalleryNamespace. If you are using some sort of custom build system, try using Build & Run instead. In the worst case, try importing the plugin to an empty Unity project and see if the issue can be reproduced.

**Comment by paulinevivier** [comment]
@volkerku did you manage to solve this issue? I'm facing the same problem. It's working fine in an empty project though.

**Comment by yasirkula** [comment]
Try creating the following script:

```csharp
namespace NativeGalleryNamespace
{
    public class MyDummyClass { }
}
```
