### ISSUE TITLE
[Android] Sharing an image with text does not show text.

### ISSUE THREAD

**Issue by andrewspalato** [yasirkula/UnityNativeShare#94]
Creating a NativeShare with image and text will not display the text, this happens when sharing via email/gmail and other apps.
I expected Facebook to only show image or text due to the fact there is a Facebook SDK which handles this.

**Reproduction steps**
- Create a new NativeShare object and add any Texture2D.
- Set title, subject, description using the built in methods from the UnityNativeShare package.

**Platform specs**
- Unity version: 2019.4.12f1
- Platform: Android
- Device: Samsung Galaxy S9+, Android 10
- How did you download the plugin: Package Manager. 

**Player Settings**
Target API level: 29
Scripting Backend: IL2CPP
API Compatibility Level: .NET Standard 2.0

**Additional info**
Logs: 
Shared on app: com.google.android.gm/com.google.android.gm.ComposeActivityGmailExternal

**Comment by yasirkula** [comment]
Is text visible in any of the social apps?

**Comment by andrewspalato** [comment]
Tweets and notes only show an image if it is added by file path or Texture2D. 
I am pretty sure with previous versions of the plugin, I was able to include images and text in one share.

**Comment by yasirkula** [comment]
I'm skeptical that I've made a change in the codebase that would cause this. You can download the previous versions from here: https://github.com/yasirkula/UnityNativeShare/releases. Can you find the latest release that didn't have this issue?

**Comment by andrewspalato** [comment]
I tried an empty minimal project but using the same projects settings as above, and it actually works correctly! 
Something must be overriding the text being used for the share. 
This requires more investigation.

**Comment by andrewspalato** [comment]
Turned out to be a race condition to populate some strings in the app I am working on. The strings were empty at the time of the sharing. I will close this issue and thank you for assistance.
