### ISSUE TITLE
Trying to share video in android on Moj(in.mohalla.video) app. App opening but not with video. 

### ISSUE THREAD

**Issue by dhruvmodhapp** [yasirkula/UnityNativeShare#95]
Hello,
I am trying to share(on android) video mp4 from my unity app to Moj app with passing 
`new NativeShare().AddTarget("in.mohalla.video").AddFile(videoPath).Share();`

on the share, it opens the Moj app but not with the recorded video. (Any other app like Instagram, Facebook, WhatsApp working fine)

I got this below android log on share:

```
I/ActivityManager: START u0 {act=android.intent.action.SEND typ=video/mp4 flg=0xb080001 pkg=in.mohalla.video cmp=in.mohalla.video/in.mohalla.sharechat.mojvideoplayer.MojVideoPlayerActivity clip={video/mp4 U:content://myapppackage.NativeShareContentProvider/devroot/storage/emulated/0/Android/data/myapppackage/files/recording_2020_11_05_10_55_20_734.mp4} (has extras)} from uid 10995
2020-11-05 11:01:29.797 2241-4007/? I/ActivityManager: Ignoring FLAG_ACTIVITY_NEW_DOCUMENT, launchMode is "singleInstance" or "singleTask"
2020-11-05 11:01:29.802 2241-4007/? D/ActivityTrigger: activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{8dece5c in.mohalla.video}
2020-11-05 11:01:29.802 2241-4007/? E/ActivityTrigger: activityStartTrigger: not whiteListedin.mohalla.video/in.mohalla.sharechat.mojvideoplayer.MojVideoPlayerActivity/91
```

Any idea to share video on android moj app? @yasirkula

**Comment by yasirkula** [comment]
If you omit AddTarget and then select Moj app, does the recorded video show up properly?

**Comment by dhruvmodhapp** [comment]
> If you omit AddTarget and then select Moj app, does the recorded video show up properly?

Thanks for your quick response.
I omit AddTarget, but still not show up with the recorded video. Please check this below video.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/46337334/98206143-70d08500-1f5f-11eb-85a5-e860351def6d.gif)

**Comment by yasirkula** [comment]
I don't see any meaningful error messages in logcat. I'm afraid I won't be able to resolve this issue. NativeShare simply passes the path of the recorded video in a standardized way (using ContentProvider with ACTION_SEND Intent) and the rest is handled by the target apps (in this case, Moj). Why Moj doesn't behave like other social apps, I really can't tell :/

**Comment by dhruvmodhapp** [comment]
> I don't see any meaningful error messages in logcat. I'm afraid I won't be able to resolve this issue. NativeShare simply passes the path of the recorded video in a standardized way (using ContentProvider with ACTION_SEND Intent) and the rest is handled by the target apps (in this case, Moj). Why Moj doesn't behave like other social apps, I really can't tell :/

Yes. target app I think not handling intent from their activity side. That is the main issue. But I noticed that from Google Photos/By default android gallery apps, can able to share the video at Moj.

**Comment by yasirkula** [comment]
I've looked at [native Gallery app's source code](https://android.googlesource.com/platform/packages/apps/Gallery/+/refs/heads/master/src/com/android/camera) for a while. The only difference in share functionality that I could find of is that, they share the image/video's existing Gallery url whereas NativeShare generates a url using ContentProvider and then shares it. Since the image/video we are sharing with NativeShare isn't included in the Gallery, there is no Gallery url for these files.
