### ISSUE TITLE
Landscape Mode

### ISSUE THREAD

**Issue by elephantmobiledev** [yasirkula/UnityNativeShare#98]
Hi. When i use portrait mode, everything works perfect but when i use landscape mode, i can't see icons of applications.

Edit: [This](https://github.com/yasirkula/UnityNativeShare/issues/86#issuecomment-674373078) works for android too. Thanks.

**Comment by yasirkula** [comment]
Were you using the latest version of the plugin?

**Comment by elephantmobiledev** [comment]
Yes I was.

**Comment by yasirkula** [comment]
What is the device's model and does it use MIUI?

**Comment by elephantmobiledev** [comment]
I have tried it on 2 devices

Vestel Venus V3 5580 / Android 7.0

Samsung Galaxy Note 3 / Android 5.0

I have done [that](https://github.com/yasirkula/UnityNativeShare/issues/86#issuecomment-674373078) and it has worked perfect.

**Comment by yasirkula** [comment]
I'm happy to hear about the resolution. Did you install MIUI operating system on these devices or was it the stock operating system that comes with the device (or maybe another custom OS)?

**Comment by elephantmobiledev** [comment]
No. I didn't install anything. They have Android 7 and Android 5. The solution is effective for Android too.

**Comment by yasirkula** [comment]
Hmm, without the fix, both of these devices had the same issue, am I right? This is the first time I'm hearing about this issue on stock Android OS so I'm surprised. I'd really appreciate it if you could temporarily undo the fix and send me a screenshot of the problematic share sheet.

**Comment by elephantmobiledev** [comment]
Yes, you are right. I thought that screenshot is unnecessary. Because when i touched the "Share" button, nothing happened. That's all.

**Comment by yasirkula** [comment]
OK now I'm relieved 😺 Probably there was an error message. Can you please check logcat for any error messages when you click the "Share" button?

**Comment by elephantmobiledev** [comment]
If I would have the same problem in the future, I will send you error messages. 

By the way, thank you so much again for share this very useful plugin with us.

**Comment by yasirkula** [comment]
You are welcome. I was asking you to undo the fix temporarily then check logcat for error messages because I can't reproduce this issue on my own and need to see the error message.
